version: "3.2"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  app:
    build:
     context: .
     dockerfile: Dockerfile
    tty: true
    environment:
    - DB_HOST
    - DB_USER
    - DB_PASSWORD
    depends_on:
      - "db"
