version: "3.2"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: "hedgehogSecretPassword"
    ports:
      - 5432:5432
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
  # app:
  #  image: elixir:1.10
  #  command: mix ecto.create && mix ecto.migrate && iex -S mix